# Generated by Django 6.0 on 2025-12-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('common', '0001_initial'),
        ('materials', '0001_initial'),
        ('rooms', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('lead_time', models.IntegerField(blank=True, null=True, verbose_name='Prazo (Dias)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.auxstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='orders.order', verbose_name='Pedido')),
                ('unit_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.auxunitmeasure', verbose_name='Unidade Medida')),
            ],
            options={
                'verbose_name': 'Material do Pedido',
                'verbose_name_plural': 'Materiais do Pedido',
                'db_table': 'orders_materials',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='orders.order', verbose_name='Pedido')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='Ambiente')),
                ('room_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roompart', verbose_name='Parte do Ambiente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do Pedido',
                'verbose_name_plural': 'Serviços do Pedido',
                'db_table': 'orders_services',
            },
        ),
    ]
