# Generated by Django 6.0.4 on 2026-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterial',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='ordermaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade'),
        ),
    ]
