# Generated by Django 5.2.17 on 2026-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='room_identifier',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do Ambiente'),
        ),
    ]
