# Generated by Django 6.0 on 2025-12-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
    ]
