# Generated by Django 6.0.4 on 2026-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_default_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Sugerido'),
        ),
    ]
