# Generated by Django 6.0 on 2025-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Contato',
                'verbose_name_plural': 'Tipos de Contato',
                'db_table': 'aux_contact_type',
            },
        ),
        migrations.CreateModel(
            name='AuxStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status Auxiliares',
                'db_table': 'aux_status',
            },
        ),
        migrations.CreateModel(
            name='AuxUnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código (Sigla)')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'aux_unit_measure',
            },
        ),
    ]
