# Generated by Django 6.0 on 2025-12-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
