# Generated by Django 6.0 on 2025-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro (Rua/Av)'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
    ]
