# Generated by Django 6.0 on 2025-12-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientaddress_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
