# Generated by Django 6.0 on 2025-12-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cômodo')),
            ],
            options={
                'verbose_name': 'Cômodo',
                'verbose_name_plural': 'Cômodos',
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Parte')),
            ],
            options={
                'verbose_name': 'Parte do Cômodo',
                'verbose_name_plural': 'Partes do Cômodo',
                'db_table': 'room_parts',
                'ordering': ['name'],
            },
        ),
    ]
